idportenEnabled: true
tokenxEnabled: true
ingress: https://dokument-proxy.ekstern.dev.nav.no
env:
  - name: LPS_API_TARGET
    value: dev-gcp:helsearbeidsgiver:sykepenger-im-lps-api
  - name: LPS_API_BASE_URL
    value: http://sykepenger-im-lps-api
  - name: JAVA_TOOL_OPTIONS
    value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
