kafkaPool: nav-dev
idportenEnabled: true
valkeyAccess: read
ingress: https://helsearbeidsgiver-im-api.intern.dev.nav.no
inboundApps:
  - name: spinntektsmelding-frontend
apps:
  - name: sykepenger-im-lps-api
    namespace: helsearbeidsgiver


